# Generated by Django 3.2.9 on 2021-11-28 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('level_id', models.AutoField(primary_key=True, serialize=False)),
                ('level_name', models.CharField(max_length=70)),
                ('level_details', models.TextField()),
                ('score_type', models.CharField(choices=[('MS', 'MaturityScore'), ('TS', 'ThreatScore')], default='MS', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('option_id', models.AutoField(primary_key=True, serialize=False)),
                ('option', models.TextField()),
                ('level_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.levels')),
            ],
        ),
    ]
