# Generated by Django 3.2.9 on 2022-03-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_levels_level_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='options',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
