# Generated by Django 3.2.9 on 2021-12-01 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0002_initial'),
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assesmeent',
            name='detect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='function.detect'),
        ),
        migrations.AlterField(
            model_name='assesmeent',
            name='identify',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='function.identify'),
        ),
        migrations.AlterField(
            model_name='assesmeent',
            name='protect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='function.protect'),
        ),
        migrations.AlterField(
            model_name='assesmeent',
            name='recover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='function.recover'),
        ),
        migrations.AlterField(
            model_name='assesmeent',
            name='respond',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='function.respond'),
        ),
    ]
