# Generated by Django 3.2.9 on 2021-12-05 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0005_alter_identify_category_id'),
        ('category', '0002_initial'),
        ('report', '0002_auto_20211201_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identifydataset',
            name='ad_maturity_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='identifydataset',
            name='category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.category'),
        ),
        migrations.AlterField(
            model_name='identifydataset',
            name='identify_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='function.identify'),
        ),
        migrations.AlterField(
            model_name='identifydataset',
            name='impact_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='identifydataset',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='identifydataset',
            name='likelihood_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='identifydataset',
            name='severity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='identifydataset',
            name='threat_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='identifydataset',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
