# Generated by Django 3.2.9 on 2022-02-13 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_alter_identifydataset_assessed_maturity_level_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='identifydataset',
            name='desired_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identify_desired_state', to='report.threatscoringtable'),
        ),
        migrations.AddField(
            model_name='identifydataset',
            name='desired_state_severity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
