# Generated by Django 3.2.9 on 2022-02-13 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_auto_20220213_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='protectdataset',
            name='desired_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='protect_desired_state', to='report.threatscoringtable'),
        ),
        migrations.AddField(
            model_name='protectdataset',
            name='desired_state_severity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='protectdataset',
            name='ad_maturity_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='protectdataset',
            name='impact_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='protectdataset',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='protectdataset',
            name='likelihood_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='protectdataset',
            name='severity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='protectdataset',
            name='threat_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='protectdataset',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
