# Generated by Django 3.2.9 on 2022-02-13 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_auto_20220213_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protectdataset',
            name='Assessed_Maturity_Level_value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='protect_Assessed_Maturity_Level_value', to='report.threatscoringtable'),
        ),
    ]
