# Generated by Django 3.2.9 on 2022-02-13 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0011_auto_20220213_2044'),
        ('category', '0004_alter_category_function_id'),
        ('report', '0008_rename_protect_id_protectdataset_identify_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protectdataset',
            name='category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.category'),
        ),
        migrations.AlterField(
            model_name='protectdataset',
            name='identify_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='function.protect'),
        ),
    ]
