# Generated by Django 3.2.9 on 2022-02-20 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_auto_20220213_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detectdataset',
            old_name='detect_id',
            new_name='identify_id',
        ),
        migrations.RenameField(
            model_name='recoverdataset',
            old_name='recover_id',
            new_name='identify_id',
        ),
        migrations.RenameField(
            model_name='responddataset',
            old_name='respond_id',
            new_name='identify_id',
        ),
        migrations.AddField(
            model_name='detectdataset',
            name='desired_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detect_desired_state', to='report.threatscoringtable'),
        ),
        migrations.AddField(
            model_name='detectdataset',
            name='desired_state_severity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='recoverdataset',
            name='desired_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recover_desired_state', to='report.threatscoringtable'),
        ),
        migrations.AddField(
            model_name='recoverdataset',
            name='desired_state_severity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='responddataset',
            name='desired_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respond_desired_state', to='report.threatscoringtable'),
        ),
        migrations.AddField(
            model_name='responddataset',
            name='desired_state_severity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='detectdataset',
            name='Assessed_Maturity_Level_value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detect_Assessed_Maturity_Level_value', to='report.threatscoringtable'),
        ),
        migrations.AlterField(
            model_name='detectdataset',
            name='ad_maturity_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detectdataset',
            name='impact_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detectdataset',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detectdataset',
            name='likelihood_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detectdataset',
            name='severity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detectdataset',
            name='threat_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detectdataset',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recoverdataset',
            name='Assessed_Maturity_Level_value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recover_Assessed_Maturity_Level_value', to='report.threatscoringtable'),
        ),
        migrations.AlterField(
            model_name='recoverdataset',
            name='ad_maturity_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recoverdataset',
            name='impact_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recoverdataset',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recoverdataset',
            name='likelihood_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recoverdataset',
            name='severity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recoverdataset',
            name='threat_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recoverdataset',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='responddataset',
            name='Assessed_Maturity_Level_value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respond_Assessed_Maturity_Level_value', to='report.threatscoringtable'),
        ),
        migrations.AlterField(
            model_name='responddataset',
            name='ad_maturity_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='responddataset',
            name='impact_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='responddataset',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='responddataset',
            name='likelihood_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='responddataset',
            name='severity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='responddataset',
            name='threat_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='responddataset',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
