# Generated by Django 3.2.9 on 2022-02-22 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_alter_category_function_id'),
        ('function', '0014_auto_20220222_2106'),
        ('report', '0010_auto_20220220_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectdataset',
            name='category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.category'),
        ),
        migrations.AlterField(
            model_name='detectdataset',
            name='identify_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='function.detect'),
        ),
        migrations.AlterField(
            model_name='recoverdataset',
            name='category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.category'),
        ),
        migrations.AlterField(
            model_name='recoverdataset',
            name='identify_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='function.recover'),
        ),
        migrations.AlterField(
            model_name='responddataset',
            name='category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.category'),
        ),
        migrations.AlterField(
            model_name='responddataset',
            name='identify_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='function.respond'),
        ),
    ]
