# Generated by Django 3.2.9 on 2021-11-28 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_index', models.IntegerField()),
                ('category_name', models.CharField(max_length=70)),
                ('category_tag', models.CharField(max_length=20)),
                ('category_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('subcategory_id', models.AutoField(primary_key=True, serialize=False)),
                ('subcategory_index', models.IntegerField()),
                ('subcategory_name', models.CharField(max_length=70)),
                ('subcategory_details', models.TextField()),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
    ]
