# Generated by Django 3.2.9 on 2021-11-28 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('function', '0001_initial'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='function_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='function.function'),
        ),
        migrations.AddField(
            model_name='category',
            name='function_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='function.function'),
        ),
    ]
