# Generated by Django 3.2.9 on 2022-01-15 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0009_auto_20220115_2006'),
        ('category', '0003_auto_20220115_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='function_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='function.function'),
        ),
    ]
