# Generated by Django 3.2.9 on 2021-11-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detect',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('MaturityScoreaverage', models.IntegerField()),
                ('MaturityRoadMapavg', models.IntegerField()),
                ('ThreatSeverityavg', models.IntegerField()),
                ('CalculatedPriorityavg', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DetectMaturityRoadMap',
            fields=[
                ('map_id', models.AutoField(primary_key=True, serialize=False)),
                ('initial_risk', models.IntegerField()),
                ('repeatable', models.IntegerField()),
                ('defined', models.IntegerField()),
                ('managed', models.IntegerField()),
                ('optimizing', models.IntegerField()),
                ('initial_risk_color', models.CharField(choices=[('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1)),
                ('repeatable_color', models.CharField(choices=[('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1)),
                ('defined_color', models.CharField(choices=[('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1)),
                ('managed_color', models.CharField(choices=[('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1)),
                ('optimizing_color', models.CharField(choices=[('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1)),
                ('assessed_maturity_level', models.CharField(choices=[('SAR', 'Select A Response'), ('NE', 'Non - Existent'), ('I', 'Initial'), ('DEV', 'Developing'), ('DEF', 'Defined'), ('M', 'Managed'), ('O', 'Optimized')], default=None, max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('function_id', models.AutoField(primary_key=True, serialize=False)),
                ('function_index', models.IntegerField()),
                ('function_name', models.CharField(max_length=70)),
                ('function_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Identify',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('MaturityScoreaverage', models.IntegerField()),
                ('MaturityRoadMapavg', models.IntegerField()),
                ('ThreatSeverityavg', models.IntegerField()),
                ('CalculatedPriorityavg', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='IdentifyMaturityRoadMap',
            fields=[
                ('map_id', models.AutoField(primary_key=True, serialize=False)),
                ('initial_risk', models.IntegerField()),
                ('repeatable', models.IntegerField()),
                ('defined', models.IntegerField()),
                ('managed', models.IntegerField()),
                ('optimizing', models.IntegerField()),
                ('initial_risk_color', models.CharField(choices=[('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1)),
                ('repeatable_color', models.CharField(choices=[('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1)),
                ('defined_color', models.CharField(choices=[('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1)),
                ('managed_color', models.CharField(choices=[('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1)),
                ('optimizing_color', models.CharField(choices=[('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1)),
                ('assessed_maturity_level', models.CharField(choices=[('SAR', 'Select A Response'), ('NE', 'Non - Existent'), ('I', 'Initial'), ('DEV', 'Developing'), ('DEF', 'Defined'), ('M', 'Managed'), ('O', 'Optimized')], default=None, max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Protect',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('MaturityScoreaverage', models.IntegerField()),
                ('MaturityRoadMapavg', models.IntegerField()),
                ('ThreatSeverityavg', models.IntegerField()),
                ('CalculatedPriorityavg', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProtectMaturityRoadMap',
            fields=[
                ('map_id', models.AutoField(primary_key=True, serialize=False)),
                ('initial_risk', models.IntegerField()),
                ('repeatable', models.IntegerField()),
                ('defined', models.IntegerField()),
                ('managed', models.IntegerField()),
                ('optimizing', models.IntegerField()),
                ('initial_risk_color', models.CharField(choices=[('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1)),
                ('repeatable_color', models.CharField(choices=[('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1)),
                ('defined_color', models.CharField(choices=[('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1)),
                ('managed_color', models.CharField(choices=[('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1)),
                ('optimizing_color', models.CharField(choices=[('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1)),
                ('assessed_maturity_level', models.CharField(choices=[('SAR', 'Select A Response'), ('NE', 'Non - Existent'), ('I', 'Initial'), ('DEV', 'Developing'), ('DEF', 'Defined'), ('M', 'Managed'), ('O', 'Optimized')], default=None, max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Recover',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('MaturityScoreaverage', models.IntegerField()),
                ('MaturityRoadMapavg', models.IntegerField()),
                ('ThreatSeverityavg', models.IntegerField()),
                ('CalculatedPriorityavg', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RecoverMaturityRoadMap',
            fields=[
                ('map_id', models.AutoField(primary_key=True, serialize=False)),
                ('initial_risk', models.IntegerField()),
                ('repeatable', models.IntegerField()),
                ('defined', models.IntegerField()),
                ('managed', models.IntegerField()),
                ('optimizing', models.IntegerField()),
                ('initial_risk_color', models.CharField(choices=[('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1)),
                ('repeatable_color', models.CharField(choices=[('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1)),
                ('defined_color', models.CharField(choices=[('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1)),
                ('managed_color', models.CharField(choices=[('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1)),
                ('optimizing_color', models.CharField(choices=[('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1)),
                ('assessed_maturity_level', models.CharField(choices=[('SAR', 'Select A Response'), ('NE', 'Non - Existent'), ('I', 'Initial'), ('DEV', 'Developing'), ('DEF', 'Defined'), ('M', 'Managed'), ('O', 'Optimized')], default=None, max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Respond',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('MaturityScoreaverage', models.IntegerField()),
                ('MaturityRoadMapavg', models.IntegerField()),
                ('ThreatSeverityavg', models.IntegerField()),
                ('CalculatedPriorityavg', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RespondMaturityRoadMap',
            fields=[
                ('map_id', models.AutoField(primary_key=True, serialize=False)),
                ('initial_risk', models.IntegerField()),
                ('repeatable', models.IntegerField()),
                ('defined', models.IntegerField()),
                ('managed', models.IntegerField()),
                ('optimizing', models.IntegerField()),
                ('initial_risk_color', models.CharField(choices=[('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1)),
                ('repeatable_color', models.CharField(choices=[('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1)),
                ('defined_color', models.CharField(choices=[('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1)),
                ('managed_color', models.CharField(choices=[('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1)),
                ('optimizing_color', models.CharField(choices=[('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1)),
                ('assessed_maturity_level', models.CharField(choices=[('SAR', 'Select A Response'), ('NE', 'Non - Existent'), ('I', 'Initial'), ('DEV', 'Developing'), ('DEF', 'Defined'), ('M', 'Managed'), ('O', 'Optimized')], default=None, max_length=3)),
            ],
        ),
    ]
