# Generated by Django 3.2.9 on 2021-11-28 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('function', '0001_initial'),
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondmaturityroadmap',
            name='dataset_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.responddataset'),
        ),
        migrations.AddField(
            model_name='respondmaturityroadmap',
            name='identify_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='function.identify'),
        ),
        migrations.AddField(
            model_name='respond',
            name='respond_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='function.function'),
        ),
        migrations.AddField(
            model_name='recovermaturityroadmap',
            name='dataset_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.recoverdataset'),
        ),
        migrations.AddField(
            model_name='recovermaturityroadmap',
            name='identify_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='function.identify'),
        ),
        migrations.AddField(
            model_name='recover',
            name='recover_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='function.function'),
        ),
        migrations.AddField(
            model_name='protectmaturityroadmap',
            name='dataset_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.protectdataset'),
        ),
        migrations.AddField(
            model_name='protectmaturityroadmap',
            name='identify_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='function.identify'),
        ),
        migrations.AddField(
            model_name='protect',
            name='protect_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='function.function'),
        ),
        migrations.AddField(
            model_name='identifymaturityroadmap',
            name='dataset_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.identifydataset'),
        ),
        migrations.AddField(
            model_name='identifymaturityroadmap',
            name='identify_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='function.identify'),
        ),
        migrations.AddField(
            model_name='identify',
            name='identify_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='function.function'),
        ),
        migrations.AddField(
            model_name='detectmaturityroadmap',
            name='dataset_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.detectdataset'),
        ),
        migrations.AddField(
            model_name='detectmaturityroadmap',
            name='identify_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='function.identify'),
        ),
        migrations.AddField(
            model_name='detect',
            name='detect_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='function.function'),
        ),
    ]
