# Generated by Django 3.2.9 on 2021-12-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identify',
            name='CalculatedPriorityavg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='identify',
            name='MaturityRoadMapavg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='identify',
            name='MaturityScoreaverage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='identify',
            name='ThreatSeverityavg',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
