# Generated by Django 3.2.9 on 2021-12-05 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_initial'),
        ('function', '0003_auto_20211201_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='identify',
            name='category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.category'),
        ),
    ]
