# Generated by Django 3.2.9 on 2021-12-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0005_alter_identify_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identifymaturityroadmap',
            name='assessed_maturity_level',
            field=models.CharField(choices=[('Select A Response', 'Select A Response'), ('Non-Existent', 'Non-Existent'), ('Initial', 'Initial'), ('Developing', 'Developing'), ('Defined', 'Defined'), ('Managed', 'Managed'), ('Optimized', 'Optimized')], default=None, max_length=20),
        ),
    ]
