# Generated by Django 3.2.9 on 2021-12-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0006_alter_identifymaturityroadmap_assessed_maturity_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identifymaturityroadmap',
            name='defined_color',
            field=models.CharField(choices=[('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='identifymaturityroadmap',
            name='initial_risk_color',
            field=models.CharField(choices=[('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='identifymaturityroadmap',
            name='managed_color',
            field=models.CharField(choices=[('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='identifymaturityroadmap',
            name='optimizing_color',
            field=models.CharField(choices=[('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='identifymaturityroadmap',
            name='repeatable_color',
            field=models.CharField(choices=[('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='protectmaturityroadmap',
            name='defined_color',
            field=models.CharField(choices=[('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='protectmaturityroadmap',
            name='initial_risk_color',
            field=models.CharField(choices=[('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='protectmaturityroadmap',
            name='managed_color',
            field=models.CharField(choices=[('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='protectmaturityroadmap',
            name='optimizing_color',
            field=models.CharField(choices=[('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='protectmaturityroadmap',
            name='repeatable_color',
            field=models.CharField(choices=[('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1, null=True),
        ),
    ]
