# Generated by Django 3.2.9 on 2021-12-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0007_auto_20211218_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectmaturityroadmap',
            name='defined_color',
            field=models.CharField(choices=[('W', 'White'), ('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='detectmaturityroadmap',
            name='initial_risk_color',
            field=models.CharField(choices=[('W', 'White'), ('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='detectmaturityroadmap',
            name='managed_color',
            field=models.CharField(choices=[('W', 'White'), ('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='detectmaturityroadmap',
            name='optimizing_color',
            field=models.CharField(choices=[('W', 'White'), ('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='detectmaturityroadmap',
            name='repeatable_color',
            field=models.CharField(choices=[('W', 'White'), ('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='identifymaturityroadmap',
            name='defined_color',
            field=models.CharField(choices=[('W', 'White'), ('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='identifymaturityroadmap',
            name='initial_risk_color',
            field=models.CharField(choices=[('W', 'White'), ('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='identifymaturityroadmap',
            name='managed_color',
            field=models.CharField(choices=[('W', 'White'), ('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='identifymaturityroadmap',
            name='optimizing_color',
            field=models.CharField(choices=[('W', 'White'), ('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='identifymaturityroadmap',
            name='repeatable_color',
            field=models.CharField(choices=[('W', 'White'), ('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='protectmaturityroadmap',
            name='defined_color',
            field=models.CharField(choices=[('W', 'White'), ('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='protectmaturityroadmap',
            name='initial_risk_color',
            field=models.CharField(choices=[('W', 'White'), ('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='protectmaturityroadmap',
            name='managed_color',
            field=models.CharField(choices=[('W', 'White'), ('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='protectmaturityroadmap',
            name='optimizing_color',
            field=models.CharField(choices=[('W', 'White'), ('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='protectmaturityroadmap',
            name='repeatable_color',
            field=models.CharField(choices=[('W', 'White'), ('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='recovermaturityroadmap',
            name='defined_color',
            field=models.CharField(choices=[('W', 'White'), ('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='recovermaturityroadmap',
            name='initial_risk_color',
            field=models.CharField(choices=[('W', 'White'), ('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='recovermaturityroadmap',
            name='managed_color',
            field=models.CharField(choices=[('W', 'White'), ('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='recovermaturityroadmap',
            name='optimizing_color',
            field=models.CharField(choices=[('W', 'White'), ('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='recovermaturityroadmap',
            name='repeatable_color',
            field=models.CharField(choices=[('W', 'White'), ('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='respondmaturityroadmap',
            name='defined_color',
            field=models.CharField(choices=[('W', 'White'), ('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='respondmaturityroadmap',
            name='initial_risk_color',
            field=models.CharField(choices=[('W', 'White'), ('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='respondmaturityroadmap',
            name='managed_color',
            field=models.CharField(choices=[('W', 'White'), ('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='respondmaturityroadmap',
            name='optimizing_color',
            field=models.CharField(choices=[('W', 'White'), ('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='respondmaturityroadmap',
            name='repeatable_color',
            field=models.CharField(choices=[('W', 'White'), ('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1),
        ),
    ]
