# Generated by Django 3.2.9 on 2022-01-15 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_alter_category_function_id'),
        ('function', '0009_auto_20220115_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identify',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identify', to='category.category'),
        ),
    ]
