# Generated by Django 3.2.9 on 2022-02-13 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_alter_category_function_id'),
        ('function', '0010_alter_identify_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='protect',
            name='category_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='protect', to='category.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='protect',
            name='CalculatedPriorityavg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='protect',
            name='MaturityRoadMapavg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='protect',
            name='MaturityScoreaverage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='protect',
            name='ThreatSeverityavg',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
