# Generated by Django 3.2.9 on 2022-02-13 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0011_auto_20220213_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protectmaturityroadmap',
            name='identify_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='function.protect'),
        ),
    ]
