# Generated by Django 3.2.9 on 2022-02-20 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0012_alter_protectmaturityroadmap_identify_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectmaturityroadmap',
            name='identify_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='function.detect'),
        ),
        migrations.AlterField(
            model_name='recovermaturityroadmap',
            name='identify_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='function.recover'),
        ),
        migrations.AlterField(
            model_name='respondmaturityroadmap',
            name='identify_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='function.respond'),
        ),
    ]
