# Generated by Django 3.2.9 on 2022-02-22 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_alter_category_function_id'),
        ('function', '0013_auto_20220220_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='detect',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detect', to='category.category'),
        ),
        migrations.AddField(
            model_name='detectmaturityroadmap',
            name='assessed_maturity_level_value',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='protectmaturityroadmap',
            name='assessed_maturity_level_value',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='recover',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recover', to='category.category'),
        ),
        migrations.AddField(
            model_name='recovermaturityroadmap',
            name='assessed_maturity_level_value',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='respond',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respond', to='category.category'),
        ),
        migrations.AddField(
            model_name='respondmaturityroadmap',
            name='assessed_maturity_level_value',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='detect',
            name='CalculatedPriorityavg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detect',
            name='MaturityRoadMapavg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detect',
            name='MaturityScoreaverage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detect',
            name='ThreatSeverityavg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detectmaturityroadmap',
            name='defined_color',
            field=models.CharField(choices=[('W', 'White'), ('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='detectmaturityroadmap',
            name='initial_risk_color',
            field=models.CharField(choices=[('W', 'White'), ('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='detectmaturityroadmap',
            name='managed_color',
            field=models.CharField(choices=[('W', 'White'), ('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='detectmaturityroadmap',
            name='optimizing_color',
            field=models.CharField(choices=[('W', 'White'), ('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='detectmaturityroadmap',
            name='repeatable_color',
            field=models.CharField(choices=[('W', 'White'), ('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='protect',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='protect', to='category.category'),
        ),
        migrations.AlterField(
            model_name='recover',
            name='CalculatedPriorityavg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recover',
            name='MaturityRoadMapavg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recover',
            name='MaturityScoreaverage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recover',
            name='ThreatSeverityavg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recovermaturityroadmap',
            name='defined_color',
            field=models.CharField(choices=[('W', 'White'), ('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='recovermaturityroadmap',
            name='initial_risk_color',
            field=models.CharField(choices=[('W', 'White'), ('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='recovermaturityroadmap',
            name='managed_color',
            field=models.CharField(choices=[('W', 'White'), ('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='recovermaturityroadmap',
            name='optimizing_color',
            field=models.CharField(choices=[('W', 'White'), ('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='recovermaturityroadmap',
            name='repeatable_color',
            field=models.CharField(choices=[('W', 'White'), ('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='respond',
            name='CalculatedPriorityavg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='respond',
            name='MaturityRoadMapavg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='respond',
            name='MaturityScoreaverage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='respond',
            name='ThreatSeverityavg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='respondmaturityroadmap',
            name='defined_color',
            field=models.CharField(choices=[('W', 'White'), ('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='respondmaturityroadmap',
            name='initial_risk_color',
            field=models.CharField(choices=[('W', 'White'), ('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='respondmaturityroadmap',
            name='managed_color',
            field=models.CharField(choices=[('W', 'White'), ('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='respondmaturityroadmap',
            name='optimizing_color',
            field=models.CharField(choices=[('W', 'White'), ('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='respondmaturityroadmap',
            name='repeatable_color',
            field=models.CharField(choices=[('W', 'White'), ('G', 'Gray'), ('O', 'Orange')], default=None, max_length=1, null=True),
        ),
    ]
